## RGB- Bild mit Tensorflow


In [18]:
#
# Führe diese Zelle aus, um die benötigten Pakete zu installieren.
# Falls du die Pakete bereits installiert hast, kannst du diese Zelle überspringen.
#
%pip install numpy
%pip install tensorflow

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [19]:
import random
import numpy as np
from PIL import Image
import tensorflow as tf

In [20]:
# Generate random hash
hash = random.getrandbits(16)
print("Hash: ", hash)

Hash:  47408


In [21]:
# Alternative 1: Mit Pillow
print ("== Alternative 1==")
img = Image.open("./input/cat.jpg" )
img.load()
img_data = np.asarray( img, dtype="int32" )
img_tensor = tf.convert_to_tensor(img_data, dtype=tf.int32)
tf.print(img_tensor)
print("Rank des Tensors: {}".format(tf.rank(img_tensor)))

== Alternative 1==
[[[183 205 219]
  [184 206 220]
  [186 208 222]
  ...
  [221 224 229]
  [221 224 229]
  [221 224 229]]

 [[183 205 219]
  [184 206 220]
  [186 208 222]
  ...
  [220 223 228]
  [220 223 228]
  [220 223 228]]

 [[183 205 219]
  [184 206 220]
  [185 207 221]
  ...
  [221 224 229]
  [221 224 229]
  [221 224 229]]

 ...

 [[210 208 213]
  [210 208 213]
  [210 208 213]
  ...
  [208 206 207]
  [208 206 207]
  [208 206 207]]

 [[210 208 213]
  [210 208 213]
  [210 208 213]
  ...
  [208 206 207]
  [208 206 207]
  [208 206 207]]

 [[210 208 213]
  [210 208 213]
  [210 208 213]
  ...
  [208 206 207]
  [208 206 207]
  [208 206 207]]]
Rank des Tensors: 3


In [22]:
# Alternative 2: Mit tf.image.decode_jpeg()
print ("== Alternative 2 == ")
img = tf.image.decode_jpeg(tf.io.read_file("./input/cat.jpg"))
print("Rank des Tensors: {}".format(tf.rank(img)))
print("Shape des Bildes: {}".format(tf.shape(img)))
print("RGB-Werte vom Pixel (x:0,y:0) :",img[0][0])

== Alternative 2 == 
Rank des Tensors: 3
Shape des Bildes: [1163 2067    3]
RGB-Werte vom Pixel (x:0,y:0) : tf.Tensor([183 205 219], shape=(3,), dtype=uint8)


In [23]:
# Alternative 3: Mit tf.image.decode_image ohne Angaben von Bildformat()
print ("== Alternative 3 == ")
img = tf.image.decode_image(tf.io.read_file("./input/cat.jpg"))
print("Rank des Tensors: {}".format(tf.rank(img)))
print("Shape des Bildes: {}".format(tf.shape(img)))
print("RGB-Werte vom Pixel (x:0,y:0) :",img[0][0])

== Alternative 3 == 
Rank des Tensors: 3
Shape des Bildes: [1163 2067    3]
RGB-Werte vom Pixel (x:0,y:0) : tf.Tensor([183 205 219], shape=(3,), dtype=uint8)
