In [1]:
import random
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [2]:
# Generate random hash
hash = random.getrandbits(16)
print("Hash: ", hash)

Hash:  11316


In [3]:
data = datasets.load_iris()
X = data.data
y = data.target

Der Einfachheit halber geben wir nur die 10 ersten Eintraegen raus

In [4]:
X_orig = X[0:10]
print(X_orig)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


### Version 1
Der Datensatz wird mit Hilfe der Min-Max-Normalisierung normalisiert. Die Werte werden auf den Bereich [0,1] abgebildet.

Die Gleichung lautet:
$$x_{new} = \frac{x - x_{min}}{x_{max} - x_{min}}$$

In [5]:
# Version 1
# Die Werte werden auf ein Interval [0 ... 1] normalisiert ...
scaler = MinMaxScaler()
X_scaled = scaler.fit_transform(X_orig)

### Version 2
Der Datensatz wird mit Hilfe der Standardisierung normalisiert.

Die Gleichung lautet:
$$x_{new} = \frac{x - \mu}{\sigma}$$

In [6]:
# Version 2

In [7]:
# ... und mit genau 3 Dezimalstellen ausgegeben
np.set_printoptions(precision=3,floatmode="fixed")
print(X_scaled)

[[0.700 0.600 0.250 0.333]
 [0.500 0.100 0.250 0.333]
 [0.300 0.300 0.000 0.333]
 [0.200 0.200 0.500 0.333]
 [0.600 0.700 0.250 0.333]
 [1.000 1.000 1.000 1.000]
 [0.200 0.500 0.250 0.667]
 [0.600 0.500 0.500 0.333]
 [0.000 0.000 0.250 0.333]
 [0.500 0.200 0.500 0.000]]
