In [7]:
#
# Beispiel einer Normalisierung von Daten 
# 
%pip install numpy
%pip install matplotlib

import numpy as np
import matplotlib.pyplot as plt

In [8]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler

In [9]:
data = datasets.load_iris()
X = data.data
y = data.target

Der Einfachheit halber geben wir nur die 10 ersten Eintraegen raus

In [10]:
X_orig = X[0:10]
print(X_orig)

[[5.100 3.500 1.400 0.200]
 [4.900 3.000 1.400 0.200]
 [4.700 3.200 1.300 0.200]
 [4.600 3.100 1.500 0.200]
 [5.000 3.600 1.400 0.200]
 [5.400 3.900 1.700 0.400]
 [4.600 3.400 1.400 0.300]
 [5.000 3.400 1.500 0.200]
 [4.400 2.900 1.400 0.200]
 [4.900 3.100 1.500 0.100]]


### Version 1
Der Datensatz wird mit Hilfe der Min-Max-Normalisierung normalisiert. Die Werte werden auf den Bereich [0,1] abgebildet.

Die Gleichung lautet:
$$x_{new} = \frac{x - x_{min}}{x_{max} - x_{min}}$$

In [11]:
# Version 1
# Die Werte werden auf ein Interval [0 ... 1] normalisiert ...
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X_orig)

### Version 2
Der Datensatz wird mit Hilfe der Standardisierung normalisiert.

Die Gleichung lautet:
$$x_{new} = \frac{x - \mu}{\sigma}$$

In [ ]:
# Version 2

In [12]:
# ... und mit genau 3 Dezimalstellen ausgegeben
np.set_printoptions(precision=3,floatmode="fixed")
print(X_scaled)

[[ 0.868  0.652 -0.488 -0.267]
 [ 0.145 -1.064 -0.488 -0.267]
 [-0.579 -0.378 -1.464 -0.267]
 [-0.941 -0.721  0.488 -0.267]
 [ 0.507  0.995 -0.488 -0.267]
 [ 1.954  2.025  2.440  2.405]
 [-0.941  0.309 -0.488  1.069]
 [ 0.507  0.309  0.488 -0.267]
 [-1.664 -1.407 -0.488 -0.267]
 [ 0.145 -0.721  0.488 -1.604]]
